version: "3.3"

services:

  analyze_module:
    image: analyze_module:latest
    environment:
      AMQP_URL: 'amqp://message_broker?connection_attempts=5&retry_delay=5'
    volumes:
      - ./theHarvester:/app/theHarvester
    networks:
      - analyze_module_network
    depends_on:
      - message_broker
    restart: on-failure

  password_module:
    image: password_module:latest
    environment:

      AMQP_URL: 'amqp://message_broker?connection_attempts=5&retry_delay=5'
    volumes:
      - ./theHarvester:/app/theHarvester
    networks:
      - password_module_network
    depends_on:
      - message_broker
    restart: on-failure

  controller_module:
    image: controller_module:latest
    environment:
      AMQP_URL: 'amqp://message_broker?connection_attempts=5&retry_delay=5'
    volumes:
      - ./controller_module/output:/app/controller_module/output
    networks:
      - controller_module_network
    depends_on:
      - message_broker
    restart: on-failure

  message_broker:
    image: 'rabbitmq:3.11-management-alpine'
    volumes:
      - rmq:/var/lib/rabbitmq
    ports:
      - '5672:5672'       # The standard AMQP protocol port
      - '15672:15672'     # HTTP management UI
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    networks:
      - analyze_module_network
      - password_module_network
      - controller_module_network
    restart: unless-stopped


networks:
  analyze_module_network:
    external: true
  password_module_network:
    external: true
  controller_module_network:
    external: true

volumes:
  rmq:
    external: true
